export const CART_STATUS_REQUEST = 'CART_STATUS_REQUEST';
export const CART_STATUS_SUCCESS = 'CART_STATUS_SUCCESS';
export const CART_STATUS_FAIL = 'CART_STATUS_FAIL';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL';

// export const USER_LOGOUT = 'USER_LOGOUT';