export const LEADERBOARD_GET_REQUEST = 'LEADERBOARD_GET_REQUEST';
export const LEADERBOARD_GET_SUCCESS = 'LEADERBOARD_GET_SUCCESS';
export const LEADERBOARD_GET_FAIL = 'LEADERBOARD_GET_FAIL';

export const RATING_UPDATE_REQUEST = 'RATING_UPDATE_REQUEST';
export const RATING_UPDATE_SUCCESS = 'RATING_UPDATE_SUCCESS';
export const RATING_UPDATE_FAIL = 'RATING_UPDATE_FAIL';

export const RATING_ADD_REQUEST = 'RATING_ADD_REQUEST';
export const RATING_ADD_SUCCESS = 'RATING_ADD_SUCCESS';
export const RATING_ADD_FAIL = 'RATING_ADD_FAIL';