export const PRODUCT_STATUS_REQUEST = 'PRODUCT_STATUS_REQUEST';
export const PRODUCT_STATUS_SUCCESS = 'PRODUCT_STATUS_SUCCESS';
export const PRODUCT_STATUS_FAIL = 'PRODUCT_STATUS_FAIL';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_POPULAR_STATUS_REQUEST = 'PRODUCT_POPULAR_STATUS_REQUEST';
export const PRODUCT_POPULAR_STATUS_SUCCESS = 'PRODUCT_POPULAR_STATUS_SUCCESS';
export const PRODUCT_POPULAR_STATUS_FAIL = 'PRODUCT_POPULAR_STATUS_FAIL';


export const PRODUCT_VENDOR_STATUS_REQUEST = 'PRODUCT_VENDOR_STATUS_REQUEST';
export const PRODUCT_VENDOR_STATUS_SUCCESS = 'PRODUCT_VENDOR_STATUS_SUCCESS';
export const PRODUCT_VENDOR_STATUS_FAIL = 'PRODUCT_VENDOR_STATUS_FAIL';


// export const PRODUCT_POPULAR_REQUEST = 'PRODUCT_POPULAR_REQUEST';
// export const PRODUCT_POPULAR_SUCCESS = 'PRODUCT_POPULAR_SUCCESS';
// export const PRODUCT_POPULAR_FAIL = 'PRODUCT_POPULAR_FAIL';





// export const USER_LOGOUT = 'USER_LOGOUT';