export const TRANSACTION_STATUS_REQUEST = 'TRANSACTION_STATUS_REQUEST';
export const TRANSACTION_STATUS_SUCCESS = 'TRANSACTION_STATUS_SUCCESS';
export const TRANSACTION_STATUS_FAIL = 'TRANSACTION_STATUS_FAIL';

export const TRANSACTION_UPDATE_REQUEST = 'TRANSACTION_UPDATE_REQUEST';
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_UPDATE_FAIL = 'TRANSACTION_UPDATE_FAIL';

export const TRANSACTION_ADD_REQUEST = 'TRANSACTION_ADD_REQUEST';
export const TRANSACTION_ADD_SUCCESS = 'TRANSACTION_ADD_SUCCESS';
export const TRANSACTION_ADD_FAIL = 'TRANSACTION_ADD_FAIL';

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL';

// export const USER_LOGOUT = 'USER_LOGOUT';